server:
  port:
    8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: movie
          uri: lb://MOVIE
          predicates:
            - Path=/api/movies/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka