server:
  port: 8082
application:
  title: 'Media list maker'
  version: 1.0.0
spring:
  application:
    name: music
  datasource:
    username: "ecommicroservice"
    url: jdbc:postgresql://localhost:5432/music
    password: "ecommicroservice"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: "true"
    hibernate:
      ddl-auto: create
    show-sql: "true"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka