services:
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: medialistmaker
      POSTGRES_PASSWORD: medialistmaker
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./table_init.sql:/docker-entrypoint-initdb.d/table_init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  registry:
    image: alexandreravichandran/medialistmaker-service-registry
    container_name: registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  gateway:
    image: alexandreravichandran/medialistmaker-service-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      registry:
        condition: service_started

  appuser:
    image: alexandreravichandran/medialistmaker-service-appuser
    container_name: appuser
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      registry:
        condition: service_started
      postgres:
        condition: service_started

  list:
    image: alexandreravichandran/medialistmaker-service-list
    container_name: list
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      registry:
        condition: service_started
      postgres:
        condition: service_started

  movie:
    image: alexandreravichandran/medialistmaker-service-movie
    container_name: movie
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - omdb.apiKey= OMDB_API_KEY
    networks:
      - spring
      - postgres
    depends_on:
      registry:
        condition: service_started
      postgres:
        condition: service_started

  music:
    image: alexandreravichandran/medialistmaker-service-music
    container_name: music
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      registry:
        condition: service_started
      postgres:
        condition: service_started

  frontend:
    image: alexandreravichandran/medialistmaker-frontend
    ports:
      - "4200:80"
    volumes:
      - .:/app


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: